### ISSUE TITLE
Cemu 1.10.0 Issue

### ISSUE THREAD

**Issue by Android4Lyfe** [CemuUser8/mouse2joystick_custom_CEMU#1]
Hey CemuUser8, I just updated my Cemu 1.9.1 to 1.10.0. My previous mouse2joystick wasn't working with Cemu 1.10.0, so I uninstalled the mouse2joystick, and installed the newer version. When I run both Cemu and the script, pressing F1 doesn't turn on the controller as I see the cursor isn't hiding and I can't use any of my keys on Legend Of Zelda : Breath Of The Wild. Please help.

**Comment by CemuUser8** [comment]
If the script isn't activating at all make sure that if you ran CEMU as admin, you also run the script as admin.

I've tested with 1.10.0 myself and haven't noticed anything different. If can confirm that they are both run with the same permissions and it is still not working could you share the contents of your settings.ini file ( Would be located in same folder as mouse2joystick)

Thank you.

**Comment by Android4Lyfe** [comment]
Thank you for helping me. I previously noticed two problems, which were the fact that I didn't run the script as admin and the input destination was set to my Cemu 1.9.1 program, not my Cemu 1.10.0. So I had to rename my Cemu 1.10 to a completely different name, and set that name as the input destination. 
Thank you for replying and helping me. And thanks again for creating this script for everyone to use.
