### ISSUE TITLE
BOTW Menu issue

### ISSUE THREAD

**Issue by famousfriend** [CemuUser8/mouse2joystick_custom_CEMU#11]
I set up the mouse2joystick with vjoy and the cemu inputs, and it seems to work in game but when i go into the menu the walk buttons to change around the menu doesn't work for some odd reason, yet I can still walk in-game and i'm stumped

**Comment by CemuUser8** [comment]
Old Issue, Closing, if it is still a problem, and you want, you can re-open or create a new one.
