### ISSUE TITLE
Mouse sensitivity issue

### ISSUE THREAD

**Issue by SyedOmarNoor** [CemuUser8/mouse2joystick_custom_CEMU#12]
The thing about the mouse sensitivity is that when I move the mouse slowly, it moves fast, and when I move the mouse quickly, it moves slower.
Is this a normal problem?

**Comment by ivansky** [comment]
I am not sure but it seems like emulating actual controller sticks can not move faster like mouse does.
It's unfortunate.
I believe there is a chance to make Camera rotation bypassing the controller layer.

**Comment by CemuUser8** [comment]
Old Issue, Closing, if it is still a problem, and you want, you can re-open or create a new one.
