### ISSUE TITLE
control issue in cemu 1.15.1

### ISSUE THREAD

**Issue by JIuBeP** [CemuUser8/mouse2joystick_custom_CEMU#13]
there was a problem, already in the menu of the game Loz Botw when you install cemu 1.15.1, I can not even load the save, the control stopped responding, although in 1.15.0 everything worked

**Comment by ZeroCool940711** [comment]
I'm having the same problem but in my case the controllers are inverted, most of the keys I setup are doing something different.

**Comment by CemuUser8** [comment]
This was most likely due to the Controller profiles being messed up after an update of CEMU, these should hopefully be fixed now.

Old Issue, Closing, if it is still a problem, and you want, you can re-open or create a new one.
