### ISSUE TITLE
Strange Issue with ZL button (Cemu, BOTW)

### ISSUE THREAD

**Issue by Denchickk** [CemuUser8/mouse2joystick_custom_CEMU#14]
For some reason everytime i press the button i bound to  ZL, instead of doing the action it is supposed to do in BOTW (deploying shield) it just says "control with wii u pro controller" im using the vBox_Gamepad preset btw
no matter to what i bind the ZL button it keeps doing that dumb thing (it also sometimes turns the camera really up when pressing the button bound to ZL)
Pls help

**Comment by INeedHelpPLLLZ** [comment]
How does your mouse2joystick still work. mine doesn't even boot.

**Comment by CemuUser8** [comment]
Sounds like an issue with the input settings, maybe it was related to the problem with Controller Profiles.

Closing, if it is still a problem, and you want, you can re-open or create a new one.
