### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by Ghostotakoi** [CemuUser8/mouse2joystick_custom_CEMU#2]
I have a pretty good feedback, lately i have been playing a game called Cuphead with your script, work fine but have some problems i will say those above:

- When i play the game in full-screen sometimes your script minimize me the game, i still can hear the game running in background even i still can press key like start for pause the game in order to maximize it again, this is fixed if i set the game to window mode but when i do this something similar happen, the game sometimes is set on background i mean the drag and drop bar turn gray, the game still running but when this happen i have to double press the button for the game receive it but only once until this happen again later.

- Other thing is that when i deactivate the script i can´t click anything i have to press ctrl - alt - del and then press the last button i pressed in the game before i deactivate the script.
sorry for my bad English and i hope you can fix it.

**Comment by CemuUser8** [comment]
Since you aren't using it with CEMU make sure that the auto activate executable is set to `No`.

For the other issue, I'm not sure what would cause that, what version of the program are you using? it says the version number on the top of the settings window.

**Comment by Ghostotakoi** [comment]
yes i have auto activate off, also the version i was using was 0.3.2.1 i have to try the new version and see if still the same.

**Comment by Ghostotakoi** [comment]
Still the same, now i tried with Nioh the version of pc, but still doing the same. i play full screen and the script minimize me the game, i already check that auto activate with cemu is off also i tried to write the name of the game exe in the script and still the same, is possible that this happen with an older version of vjoy? i can acsees to the vjoy official page because they have banned my country cuba.

**Comment by Ghostotakoi** [comment]
Done, last vjoy installed and auto hotkey installed and still the same issue, the script minimize the games when i played in full screen

**Comment by CemuUser8** [comment]
I don't see anywhere in the code that would be minimizing anything... it does activate an invisible GUI over the screen, maybe that is interfering somehow. I will look into a way to make that invisible window optional and that way you can test whether it helps to not show it at all.

**Comment by CemuUser8** [comment]
Old Issue, Closing, if it is still a problem, and you want, you can re-open or create a new one.
