### ISSUE TITLE
Pressing F1 resulting in pretty much nothing

### ISSUE THREAD

**Issue by aaRWhiZ** [CemuUser8/mouse2joystick_custom_CEMU#33]
Instructions were followed correctly and final configuration matches the images posted in the page. The varying factor in the case seems to be the fact that the PC is run in Windows 11. I tried its compatibility mode of Windows 8, still no use - Pressing F1 doesn't do anything. How can it be resolved?

**Comment by sripadks** [comment]
I am using this in Win11. Please tell me what version of Cemu you are using. There is a known bug in Cemu 1.26.1 (latest as of writing) with input methods. Try using Cemu 1.25.6 and see if it fixes the problems.

**Comment by aaRWhiZ** [comment]
> I am using this in Win11. Please tell me what version of Cemu you are using. There is a known bug in Cemu 1.26.1 (latest as of writing) with input methods. Try using Cemu 1.25.6 and see if it fixes the problems.

Thank you for the Reply. The Problem just resolved itself after extracting the Script 4 or 5 times and running it. I seriously dont know what changed, It just works now completely fine.
