### ISSUE TITLE
Few keys not working...

### ISSUE THREAD

**Issue by Pxtixnce** [CemuUser8/mouse2joystick_custom_CEMU#42]
![image_2023-03-08_145721564](https://user-images.githubusercontent.com/74662009/223674940-02f40e40-d2f0-4d12-a7c7-26d2bc41c925.png)
im playing legend of zelda breath of the wild on cemu using mouse2joystick im using the BOTW preset but the + ,-,dpadup,dpaddown,dpadleft,dpadright keys are not working.

**Comment by nissoumeg** [comment]
i have the exact same problem , how did you fix it ?

**Comment by Teslestien** [comment]
Dude don't close issues without telling other how you fixed it man
