### ISSUE TITLE
Won't start with hotkey unless settings is open and on top

### ISSUE THREAD

**Issue by Mage-Enderman** [CemuUser8/mouse2joystick_custom_CEMU#5]
I can't just press F1 to start it without settings being open and the selected window

**Comment by CemuUser8** [comment]
Sounds like you run CEMU as an admin, and not the script.

This makes it so that the F1 key press can't be detected while CEMU is the active window.

**Comment by Mage-Enderman** [comment]
I do not run Cemu as an admin but I will try running the script as an admin
