### ISSUE TITLE
Cannot set a mouse button no matter if I'm in autocycle or normally changing keys.

### ISSUE THREAD

**Issue by dominikaaaa** [CemuUser8/mouse2joystick_custom_CEMU#6]
So I cannot click inside or outside the box when the box is selected in order to set a keybind to the mouse. I have everything latest version as of yesterday (16/01/18).

**Comment by Mukkun-AI** [comment]
it can be done manually by typing (in the ini file or the from the gui) RButton LButton or MButton respectively for right left and middle mouse buttons

**Comment by CemuUser8** [comment]
Old Issue, Closing, if it is still a problem, and you want, you can re-open or create a new one.
