### ISSUE TITLE
Mousetojoystick Crash

### ISSUE THREAD

**Issue by Demannu35** [CemuUser8/mouse2joystick_custom_CEMU#7]
On my other computer I was running 1.11.3 version of Cemu with latest Hook it worked perfect. On new comp. Your app crashes as soon as I hit F1 (using 1.11.5 cemu) (fresh installs of all applications)

my setup is amazon.co.uk 17-an002na

**Comment by CemuUser8** [comment]
Old Issue, Closing, if it is still a problem, and you want, you can re-open or create a new one.
