### ISSUE TITLE
Mouse2Joystick Active KeyList does not support '=' as a mapable key

### ISSUE THREAD

**Issue by QDP22** [CemuUser8/mouse2joystick_custom_CEMU#8]
Setting up a M&K CEMU build I found that whenever the '=' key is mapped to any slot, all keys listed after that key are wiped from the save.

Not a game-breaker, can simply map the keyboard keys to other buttons. Just thought it was worth noting so a note could be added to the game, or a correction/error popup script could be added to the files.

**Comment by CemuUser8** [comment]
It is because the list is stored in an ini file, and the = causes my parsing of that to be messed up.

For now I added it along with the comma to be restricted, which means there won't be any errors but it will not even try to record it as a key.
